export type BranchType = {
  id: number;
  entity_id: number;
  registered: number;
  phone_verified: number;
  gst_number: string;
  is_default: number;
  pincode: string;
  state_name: string;
  state_code: string;
  state_id: number | null;
  branch: string;
  unit_type: string;
  address1: string | null;
  address2: string | null;
  city: string;
  city_id: number | null;
  created_at: string;
  updated_at: string | null;
  deleted_at: string | null;
  deactivated_at: string | null;
};

export type BankType = {
  id: number;
  entity_id: number;
  beneficiary_name: string;
  account_number: string;
  bank_name: string;
  ifsc_code: string;
  is_default: number;
  created_at: string;
  updated_at: string;
};

export type UserType = {
  id: number;
  first_name: string;
  last_name: string;
  salutation: string;
  email: string;
  mobile_no: string;
  calling_code: string;
  signup_brand: string;
  email_verification: number;
  mobile_verification: number;
  api_key: string;
  access_token: string;
  id_token: string;
  refresh_token: string;
  authorization_code: string;
  ambassador_link: string;
  referred_by_id: number;
  name: string;
  is_active: number;
  entity_id: number;
  entity_name: string;
  entity: {
    id: number;
    entity_name: string;
    entity_type: string;
    kyc_status: number;
    aadhaar_status: number;
    is_active: number;
    credit_limit: string;
    credit_period: number;
    member_type: string;
    logo: string;
    entity_slug: null;
    signature: string;
    kyc_verified: number;
    slug: string;
    gst_registered: number;
    pan_card: string;
    credit_balance: string;
    cod_adjustable: number;
  };
  branches?: BranchType[];
  banks?: BankType[];
  is_admin: boolean;
  role_id: number;
  is_duplicate_pan: boolean;
};
